---
- apt: name={{ item }} state=latest
  with_items:
    - expect
    - mysql-client
    - mysql-server
    - python-mysqldb
- lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line=bind-address=0.0.0.0
- service: name=mysql state=restarted enabled=yes
- copy: src=files/mysql_secure_installation.sh
        dest=/root/mysql_secure_installation.sh
        mode=0755
- command: /root/mysql_secure_installation.sh
           creates=/root/mysql_secure_installation.done
- copy: src=files/client.my.cnf dest=/root/.my.cnf
- mysql_db: name=faafo state=present
- mysql_user: name=faafo password=secretsecret priv=*.*:ALL host=localhost state=present
